
GET http://localhost:8000/inscription

###
POST http://localhost:8000/inscription HTTP/1.1
Content-Type: application/json

{
  "name": "   Ramoon",
  "lastname": "    Perez",
  "email": "ramnn.perez@gmail.com",
  "numberCell":"+543743519395",
  "locationOrigin":"Jardin America",
  "distanceTour": "40km",
  "DNI": "4123915",
  "provinceOrigin":"Misiones",
  "locationOrigin":"Jardín América",
  "almuerzo":"true"
}
### 
GET http://localhost:8000/inscription/length HTTP/1.1
